[build]
  command = "bash ./netlify/build.sh"
  publish = "build/web"

[[redirects]]
  from = "/api/ms_auth/*"
  to = "/.netlify/functions/ms_auth_proxy"
  status = 200
  force = true

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/stash/*"
  to = "/.netlify/functions/stash_proxy"
  status = 200
  force = true

[[redirects]]
  from = "/api/graph/*"
  to = "https://graph.microsoft.com/:splat"
  status = 200
  force = true

# Route all paths to the SPA entry so client-side routing works.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

