name: localflix
description: "LocalFlix: local-only Netflix-style media library"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2         # state management
  file_picker: ^8.1.2      # folder/file picker (desktop + mobile)
  path: ^1.9.0             # path helpers
  http: ^1.2.2             # OMDb + AniList calls
  shared_preferences: ^2.3.3 # local persistence & caching
  collection: ^1.18.0
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_windows_video: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true